=== Tunell/xmlChat/winChatClient/message.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT message (header, body)>
  <!ELEMENT header (protocol, id)>
    <!ELEMENT protocol (type, version, command)>
      <!ELEMENT type (#PCDATA)>
      <!ELEMENT version (#PCDATA)>
      <!ELEMENT command (#PCDATA)>
    <!ELEMENT id (name, email, homepage, host)>
      <!ELEMENT name (#PCDATA)>
      <!ELEMENT email (#PCDATA)>
      <!ELEMENT homepage (#PCDATA)>
      <!ELEMENT host (#PCDATA)>
  <!ELEMENT body (#PCDATA)
>

=== Tunell/xmlChat/winChatClient/bin/Debug/message1.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE message SYSTEM "message.dtd"><message><header><protocol><type>PelleMsg</type><version>1.0</version><command>CommandSendMsg</command></protocol><id><name>Pelle</name><email>Pelle@go.com</email><homepage>www.tfk.com</homepage><host>HostPelle</host></id></header><body>medelande av pelle</body></message>

=== Tunell/xmlChat/winChatServer/XMLFile1.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE message SYSTEM "message.dtd">
<message>
  <header>
    <protocol>
      <type>Pellemsg</type>
      <version>1.0 </version>
      <command>sendMsg</command>
    </protocol>
    <id>
      <name>Pelle</name>
      <email>Pelle@team-flashkick.com</email>
      <homepage>www.team-flashkick.com</homepage>
      <host>host</host>
    </id>
  </header>
  <body>This is the message!</body>
</message>

=== Tunell/xmlChat/winChatServer/bin/Debug/message.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE message SYSTEM "message.dtd"[]><message><header><protocol><type>PelleMsg</type><version>1.0</version><command>sendMsg</command></protocol><id><name>erwterw</name><email>pelle@mailpunktse</email><homepage>www.tfk.com</homepage><host>pelle</host></id></header><body>d</body></message>
